project_id = "zicezkodnaghvoroiswm"

[functions.send-reminders]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.update-gmail-settings]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.rate-limit-auth]
verify_jwt = false
