project_id = "otmikczyvabizskrtziw"

[functions.telegram-webhook]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.update-gmail-settings]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.rate-limit-auth]
verify_jwt = false
